name: unittest_pytest_coverage_doc

on:
  push:
    branches: [ main ]

jobs:

  macos-1015_test:
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v3
    - name: check all modules available
      run: env python3 setup.py check_modules
    - name: install pfu
      run: sudo pip3 install .
    - name: run pfu
      run: |
        which pfu
        pfu -h
        pfu simscrub -h
        pfu create_checksum -h
        pfu check_checksum -h
        pfu replicate -h
        pfu speed_test -h
    - name: unittest
      run: env python3 setup.py run_unittest
    - name: install dependencies via pip3
      run: pip3 install wheel pytest pytest-cov pytest-xdist
    - name: pytest
      run: env python3 setup.py run_pytest --parallel --coverage

  macos-11_test:
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - name: check all modules available
      run: env python3 setup.py check_modules
    - name: install pfu
      run: sudo pip3 install .
    - name: run pfu
      run: |
        which python3
        which pfu
        pfu -h
        pfu simscrub -h
        pfu create_checksum -h
        pfu check_checksum -h
        pfu replicate -h
        pfu speed_test -h
    - name: unittest
      run: env python3 setup.py run_unittest
    - name: install dependencies via pip3
      run: pip3 install wheel pytest pytest-cov pytest-xdist
    - name: pytest
      run: env python3 setup.py run_pytest --parallel --coverage

  macos-12_test:
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: check all modules available
      run: env python3 setup.py check_modules
    - name: install pfu
      run: sudo pip3 install .
    - name: run pfu
      run: |
        which python3
        which pfu
        pfu -h
        pfu simscrub -h
        pfu create_checksum -h
        pfu check_checksum -h
        pfu replicate -h
        pfu speed_test -h
    - name: unittest
      run: env python3 setup.py run_unittest
    - name: install dependencies via pip3
      run: pip3 install wheel pytest pytest-cov pytest-xdist
    - name: pytest
      run: env python3 setup.py run_pytest --parallel --coverage

  freebsd_test:
    # https://github.com/marketplace/actions/freebsd-vm
    runs-on: macos-12
    name: run tests on FreeBSD
    steps:
    - uses: actions/checkout@v3
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: true
        prepare: pkg install -y devel/py-setuptools devel/py-pytest devel/py-pytest-cov devel/py-pytest-xdist
        run: |
          set -e -x
          cat /etc/os-release
          pwd
          ls -lah
          whoami
          freebsd-version
          which python3.8
          ls -lah /usr/local/bin/python*
          python3.8 setup.py install --record installed_files.txt
          which pfu
          pfu -h
          pfu simscrub -h
          pfu create_checksum -h
          pfu check_checksum -h
          pfu replicate -h
          pfu speed_test -h
          python3.8 setup.py run_unittest
          python3.8 setup.py run_pytest --parallel --coverage
          cat installed_files.txt | xargs rm -rf && echo "uninstalled/removed: "$(cat installed_files.txt)
